name: Canary Build and Test

on:
  push:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  build_type: Release
  cpp_compiler: g++
  output_folder: ${{github.workspace}}/build/

jobs:
  Canary-Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Configure CMake
      env:
        # Map from C++ compiler to equivalent C compiler
        g++: gcc
        clang++: clang
      run: >
        cmake -S . -B "${{ env.output_folder }}"
        -DCMAKE_C_COMPILER=${{ env[env.cpp_compiler] }}
        -DCMAKE_CXX_COMPILER=${{ env.cpp_compiler }}
        -DLIBDIVIDE_BUILD_TESTS=ON
        -DCMAKE_BUILD_TYPE=${{ env.build_type }}

    - name: Build
      run: >
        cmake --build "${{ env.output_folder }}"
        --target tester
        --config ${{ env.build_type }}

    - name: Test
      working-directory: ${{env.output_folder}}
      run: ctest --build-config ${{env.build_type}} --verbose --tests-regex tester

  # Kick off the full build if everything above succeeded
  Full-Build:
    needs: Canary-Build
    uses: ./.github/workflows/full_build.yml

  # Kick off the full build if everything above succeeded
  AVR-Build:
    needs: Canary-Build
    uses: ./.github/workflows/avr_build_test.yml
